name       : xorg-driver-video-voodoo
version    : 1.4.7
release    : 4
source     :
    - https://www.x.org/archive/individual/driver/xf86-video-tdfx-1.4.7.tar.bz2 : 4cf48ee14ead52b23493c3dce5032496fd68bf1d000170bb138730497e212a42
license    : MIT
component  : xorg.driver
optimize   :
    - no-bind-now
    - no-symbolic
summary    : Voodoo Video Driver
description: |
    The Xorg 3Dfx Driver package contains the X.Org Video Driver for 3Dfx video cards including Voodoo Banshee, Voodoo3, Voodoo4 and Voodoo5 chipsets.
builddeps  :
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
    - pkgconfig(xorg-macros)
    - pkgconfig(xorg-server)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
