name       : xorg-driver-video-voodoo
version    : 1.5.0
release    : 7
source     :
    - https://www.x.org/releases/individual/driver/xf86-video-tdfx-1.5.0.tar.gz : 3128bb885d9df7b388537ec16fc565ffed51ba0d893eac936019e8ad6a1e3c41
license    : MIT
component  : xorg.driver
optimize   :
    - no-bind-now
    - no-symbolic
summary    : Voodoo Video Driver
description: |
    The Xorg 3Dfx Driver package contains the X.Org Video Driver for 3Dfx video cards including Voodoo Banshee, Voodoo3, Voodoo4 and Voodoo5 chipsets.
builddeps  :
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
    - pkgconfig(xorg-macros)
    - pkgconfig(xorg-server)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
